//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> AuthorId { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<System.DateTime> AdditionDate { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    
        public virtual User Author { get; set; }
    }
}
